name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  repository-projects: write
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write

jobs:
  call-workflow-passing-date:
    uses: Payal412/GitHub-Actions-Terrafrom-ReadmeCreation/.github/workflows/automate-readmefile.yml@main

  terraform:
    name: Terraform
    runs-on: ubuntu-latest   # Run the workflow on an Ubuntu runner

    # Use the bash shell regardless weather the GitHub Actions runner is ubuntu-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3     # Checkout the repository code

        # Install the latest version of Terraform and configure the terraform configuration file with a Terraform local user token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # You can change this to your desired version

      - name: Setup Terraform Docs
        uses: terraform-docs/gh-actions@v1.0.0    # Actions to generate Terraform documentation
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"

        #  Initialize a new or existing Terraform working directoty by creating initial files, loading any remote state, downloading modules, etc…
      - name: Terraform Init
        run: terraform init
